version: '3.9'

networks:
  default:
    driver: bridge

services:
  elasticsearch:
    image: elasticsearch:7.17.2
    restart: always
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - default

  kibana:
    image: kibana:7.17.2
    restart: always
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - default